name: freecad-to-png
permissions:
  contents: write

# execute this workflow automatically, but only when pushing to main
on:
  push:
    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:

  linux:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:

    - uses: actions/checkout@v3

    - name: Update CAD Screenshot
      shell: bash
      run: |
        set -x
        set +e

        # install depends
        sudo apt-get update
        sudo apt-get install python3 freecad

        ls -lah

        # generate the screenshot file
        ./freecad-to-png.py

        # post-run debug checks
        echo
        sleep 1
        date
        cat /etc/issue
        uname -a
        dpkg -l
        ls -lah

        # push new README to GitHub
        git config --global user.name 'maltfield'
        git config --global user.email 'michael@michaelaltfield.net'
        git add -f docs/images
        git commit -am "Auto-update"
        git push
